package main

// file generated by
// github.com/mh-cbon/http-clienter
// do not edit

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/gorilla/mux"
	"io"
	"net/http"
	"net/url"
	"strings"
)

var xxNetHTTP = http.StatusOK
var xxNetURL = url.PathEscape
var xxFmt = fmt.Println
var xxIo = io.Copy
var xxStrings = strings.Replace
var xxBytes = bytes.Compare

// HTTPClientController is an http-clienter of *Controller.
// Controller of some resources.
type HTTPClientController struct {
	router *mux.Router
	embed  *http.Client
	Base   string
}

// NewHTTPClientController constructs an http-clienter of *Controller
func NewHTTPClientController(router *mux.Router, embed *http.Client) *HTTPClientController {
	ret := &HTTPClientController{
		router: router,
		embed:  embed,
	}
	return ret
}

// GetByID constructs a request to /{id}
func (t HTTPClientController) GetByID(urlID int) (*http.Response, error) {
	var ret *http.Request
	var body io.Reader
	// var err error

	surl := "/{id}"
	surl = strings.Replace(surl, "{id}", fmt.Sprintf("%v", urlID), 1)
	url, URLerr := url.ParseRequestURI(surl)
	if URLerr != nil {
		return nil, URLerr
	}
	finalUrl := url.String()
	finalUrl = fmt.Sprint("%v%v", t.Base, finalUrl)

	req, reqErr := http.NewRequest("GET", finalUrl, body)
	if reqErr != nil {
		return nil, reqErr
	}
	ret = req

	return t.embed.Do(ret)
}

// UpdateByID constructs a request to /{id}
func (t HTTPClientController) UpdateByID(urlID int, reqBody *Tomate) (*http.Response, error) {
	var ret *http.Request
	var body io.Reader
	// var err error

	data, reqBodyErr := json.Marshal(reqBody)
	if reqBodyErr != nil {
		return nil, reqBodyErr
	}

	body = bytes.NewBuffer(data)
	surl := "/{id}"
	surl = strings.Replace(surl, "{id}", fmt.Sprintf("%v", urlID), 1)
	url, URLerr := url.ParseRequestURI(surl)
	if URLerr != nil {
		return nil, URLerr
	}
	finalUrl := url.String()
	finalUrl = fmt.Sprint("%v%v", t.Base, finalUrl)

	req, reqErr := http.NewRequest("GET", finalUrl, body)
	if reqErr != nil {
		return nil, reqErr
	}
	ret = req

	return t.embed.Do(ret)
}

// DeleteByID constructs a request to /{id}
func (t HTTPClientController) DeleteByID(REQid int) (*http.Response, error) {
	var ret *http.Request
	var body io.Reader
	// var err error

	surl := "/{id}"
	surl = strings.Replace(surl, "{id}", fmt.Sprintf("%v", REQid), 1)
	url, URLerr := url.ParseRequestURI(surl)
	if URLerr != nil {
		return nil, URLerr
	}
	finalUrl := url.String()
	finalUrl = fmt.Sprint("%v%v", t.Base, finalUrl)

	req, reqErr := http.NewRequest("GET", finalUrl, body)
	if reqErr != nil {
		return nil, reqErr
	}
	ret = req

	return t.embed.Do(ret)
}
